name: ocean-bgc-cookbook-dev
channels:
  - conda-forge
dependencies:
  - cartopy
  - cftime
  - dask
  - dask-jobqueue
  - distributed
  - h5netcdf
  - ipykernel
  - ipywidgets
  - jupyterlab
  - jupyterlab-myst
  - jupyter_server
  - matplotlib
  - metpy
  - mystmd
  - nc-time-axis
  - numpy
  - pandas
  - pip
  - pop-tools
  - rioxarray
  - s3fs
  - xarray
  - zarr
